### ISSUE TITLE
Memory access error on Windows, if free in nWrapString enabled

### ISSUE THREAD

**Issue by bsrdjan** [SAP/gorfc#1]
Memory access error occurs on Windows only, when trying to free RFCCHAR1 of RFCTABLE in function call test. As a workaround, the [line 281](https://github.com/SAP/gorfc/blob/master/gorfc/gorfc.go#L281) is commented (no malloc free!) and the usage on Windows is still experimental. Should be hopefully fixed by proper compiler switches combination.

Uncomment on Linux.

**Comment by wusj521** [comment]
Can you run on win7 32bit?

**Comment by sabatale** [comment]
Thanks for the insight! Are there any plans for Windows?

Or is this project not maintained anymore?

**Comment by bsrdjan** [comment]
The Windows is not supported until #21 fixed

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project.
