### ISSUE TITLE
Segfault RfcUTF8ToSAPUC

### ISSUE THREAD

**Issue by STiAT** [SAP/gorfc#11]
OS: Win10
go version go1.10.1 windows/amd64
nwrfcsdk version 7.20 x86/64

the function fillString causes a segfault at line 96 callling RfcUTF8ToSAPUC in the nwrfcsdk. Looking at the code it looks fine for me though.

**Comment by JonasDann** [comment]
We had seemingly random segfaults on Windows before. I at the moment cannot propose a solution, but just know that Windows is still experimental because of such problems.

**Comment by bsrdjan** [comment]
Should be fixed in 0.1.0

**Comment by STiAT** [comment]
I'll try to give feedback within this or next week. While I implemented that in another language by now, it'll be a good test.

**Comment by bsrdjan** [comment]
The Windows is not supported until #21 fixed

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project.
