### ISSUE TITLE
CGO (compiler) error in linux

### ISSUE THREAD

**Issue by lulouis** [SAP/gorfc#13]
Dear sap engineers:

I'm an experienced LinuxOS developer,I know something about gcc compiler and dynamic libraries call.
But now,CGO compiler throw  error like this picture .

Thanks very much , sir.
Louis ,Shenzhen.

![深度截图_选择区域_20190402152718](https://user-images.githubusercontent.com/8636491/55384552-94e70b80-555d-11e9-9ae2-2bbeb14362a2.png)

**Comment by antihax** [comment]
Remove all that junk. Ended up with this:
```
#cgo linux CFLAGS: -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DSAPonUNIX
#cgo linux CFLAGS: -DSAP_UC_is_wchar -DSAPwithUNICODE -D__NO_MATH_INLINES -DSAPwithTHREADS -DSAPonLIN
#cgo linux CFLAGS: -O2 -g
#cgo linux CFLAGS: -pthread -pipe -Wno-unused-variable

#cgo linux CFLAGS: -I/usr/local/sap/nwrfcsdk/include
#cgo linux LDFLAGS: -L/usr/local/sap/nwrfcsdk/lib -lsapnwrfc -lsapucum

#cgo linux LDFLAGS: -O2 -g
#cgo linux LDFLAGS: -pthread
```

**Comment by MinasWang** [comment]
# export CGO_LDFLAGS_ALLOW=".*" 
# export CGO_CFLAGS_ALLOW=".*"

after add it to whitelist, "go build" work.
