### ISSUE TITLE
Example program "hello_gorfc", sometimes it works and sometimes it doesn't 

### ISSUE THREAD

**Issue by paparipote** [SAP/gorfc#22]
Hello, I compiled the source program "hello_gorfc.go" that you have as an example. The environment is Windows 10, using go 1.14.3, and  the last version of  sapnwrfc (7.50.6).
When I execute this program many times in a minute, sometimes I get the expected results displayed and sometimes it displays nothing, there is not a uniform behavior.
I also have some programs I wrote and the behavior of these is the same; what do you thing Is happening?
Try the example program, may be you can have the same results.
Best regards.

**Comment by bsrdjan** [comment]
Yes, the results are the same.

Please see #21 and [go/#39127](https://github.com/golang/go/issues/39127) for more details about challenges with Windows.

**Comment by bsrdjan** [comment]
The Windows is not supported until #21 fixed

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project.
