### ISSUE TITLE
Error while calling GetFunctionDescription

### ISSUE THREAD

**Issue by faisal097** [SAP/gorfc#25]
Hello, I am trying to call **GetFunctionDescription** function for my Function in SAP. I am getiing following error:

**go version go1.12 linux/amd64**

`
*** glibc detected *** ./hello_gorfc: free(): invalid next size (fast): 0x0000000000cc3590 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3800c75dee]
/lib64/libc.so.6[0x3800c78c80]
./hello_gorfc[0x454630]
======= Memory map: ========
00400000-00597000 r-xp 00000000 fd:05 806929                             /home/faisal/goPath/src/github.com/sap/gorfc/example/hello_gorfc
00796000-007ab000 rw-p 00196000 fd:05 806929                             /home/faisal/goPath/src/github.com/sap/gorfc/example/hello_gorfc
007ab000-007c9000 rw-p 00000000 00:00 0
00c58000-00d47000 rw-p 00000000 00:00 0                                  [heap]
3800400000-3800420000 r-xp 00000000 fd:00 393246                         /lib64/ld-2.12.so
3800620000-3800621000 r--p 00020000 fd:00 393246                         /lib64/ld-2.12.so
3800621000-3800622000 rw-p 00021000 fd:00 393246                         /lib64/ld-2.12.so
3800622000-3800623000 rw-p 00000000 00:00 0
3800800000-3800802000 r-xp 00000000 fd:00 393600                         /lib64/libdl-2.12.so
3800802000-3800a02000 ---p 00002000 fd:00 393600                         /lib64/libdl-2.12.so
3800a02000-3800a03000 r--p 00002000 fd:00 393600                         /lib64/libdl-2.12.so
3800a03000-3800a04000 rw-p 00003000 fd:00 393600                         /lib64/libdl-2.12.so
3800c00000-3800d8a000 r-xp 00000000 fd:00 393264                         /lib64/libc-2.12.so
3800d8a000-3800f8a000 ---p 0018a000 fd:00 393264                         /lib64/libc-2.12.so
3800f8a000-3800f8e000 r--p 0018a000 fd:00 393264                         /lib64/libc-2.12.so
3800f8e000-3800f90000 rw-p 0018e000 fd:00 393264                         /lib64/libc-2.12.so
3800f90000-3800f94000 rw-p 00000000 00:00 0
3801000000-3801017000 r-xp 00000000 fd:00 393297                         /lib64/libpthread-2.12.so
3801017000-3801217000 ---p 00017000 fd:00 393297                         /lib64/libpthread-2.12.so
3801217000-3801218000 r--p 00017000 fd:00 393297                         /lib64/libpthread-2.12.so
3801218000-3801219000 rw-p 00018000 fd:00 393297                         /lib64/libpthread-2.12.so
3801219000-380121d000 rw-p 00000000 00:00 0
3801400000-3801407000 r-xp 00000000 fd:00 393669                         /lib64/librt-2.12.so
3801407000-3801606000 ---p 00007000 fd:00 393669                         /lib64/librt-2.12.so
3801606000-3801607000 r--p 00006000 fd:00 393669                         /lib64/librt-2.12.so
3801607000-3801608000 rw-p 00007000 fd:00 393669                         /lib64/librt-2.12.so
3801800000-3801883000 r-xp 00000000 fd:00 393284                         /lib64/libm-2.12.so
3801883000-3801a82000 ---p 00083000 fd:00 393284                         /lib64/libm-2.12.so
3801a82000-3801a83000 r--p 00082000 fd:00 393284                         /lib64/libm-2.12.so
3801a83000-3801a84000 rw-p 00083000 fd:00 393284                         /lib64/libm-2.12.so
3803000000-3803016000 r-xp 00000000 fd:00 393291                         /lib64/libgcc_s-4.4.7-20120601.so.1
3803016000-3803215000 ---p 00016000 fd:00 393291                         /lib64/libgcc_s-4.4.7-20120601.so.1
3803215000-3803216000 rw-p 00015000 fd:00 393291                         /lib64/libgcc_s-4.4.7-20120601.so.1
3803c00000-3803c04000 r-xp 00000000 fd:00 393673                         /lib64/libuuid.so.1.3.0
3803c04000-3803e03000 ---p 00004000 fd:00 393673                         /lib64/libuuid.so.1.3.0
3803e03000-3803e04000 rw-p 00003000 fd:00 393673                         /lib64/libuuid.so.1.3.0
3ab9200000-3ab92e8000 r-xp 00000000 fd:00 2885907                        /usr/lib64/libstdc++.so.6.0.13
3ab92e8000-3ab94e8000 ---p 000e8000 fd:00 2885907                        /usr/lib64/libstdc++.so.6.0.13
3ab94e8000-3ab94ef000 r--p 000e8000 fd:00 2885907                        /usr/lib64/libstdc++.so.6.0.13
3ab94ef000-3ab94f1000 rw-p 000ef000 fd:00 2885907                        /usr/lib64/libstdc++.so.6.0.13
3ab94f1000-3ab9506000 rw-p 00000000 00:00 0
c000000000-c004000000 rw-p 00000000 00:00 0
7ffba0000000-7ffba0021000 rw-p 00000000 00:00 0
7ffba0021000-7ffba4000000 ---p 00000000 00:00 0
7ffba5a2c000-7ffba6a2d000 rw-p 00000000 00:00 0
7ffba6a2d000-7ffba7e00000 r--p 00000000 fd:05 806053                     /home/faisal/sap/linux/nwrfcsdk/lib/libicudata.so.50
7ffba7e00000-7ffba7fff000 ---p 013d3000 fd:05 806053                     /home/faisal/sap/linux/nwrfcsdk/lib/libicudata.so.50
7ffba7fff000-7ffba8000000 r--p 013d2000 fd:05 806053                     /home/faisal/sap/linux/nwrfcsdk/lib/libicudata.so.50
7ffba8000000-7ffba8021000 rw-p 00000000 00:00 0
7ffba8021000-7ffbac000000 ---p 00000000 00:00 0
7ffbac4fd000-7ffbac50a000 r-xp 00000000 fd:00 393247                     /lib64/libnss_files-2.12.so
7ffbac50a000-7ffbac709000 ---p 0000d000 fd:00 393247                     /lib64/libnss_files-2.12.so
7ffbac709000-7ffbac70a000 r--p 0000c000 fd:00 393247                     /lib64/libnss_files-2.12.so
7ffbac70a000-7ffbac70b000 rw-p 0000d000 fd:00 393247                     /lib64/libnss_files-2.12.so
7ffbac716000-7ffbac817000 rw-p 00000000 00:00 0
7ffbac817000-7ffbaca56000 r-xp 00000000 fd:05 806056                     /home/faisal/sap/linux/nwrfcsdk/lib/libicui18n.so.50
7ffbaca56000-7ffbacc56000 ---p 0023f000 fd:05 806056                     /home/faisal/sap/linux/nwrfcsdk/lib/libicui18n.so.50
7ffbacc56000-7ffbacc63000 r--p 0023f000 fd:05 806056                     /home/faisal/sap/linux/nwrfcsdk/lib/libicui18n.so.50
7ffbacc63000-7ffbacc64000 rw-p 0024c000 fd:05 806056                     /home/faisal/sap/linux/nwrfcsdk/lib/libicui18n.so.50
7ffbacc64000-7ffbacc65000 rw-p 00000000 00:00 0
7ffbacc65000-7ffbace3a000 r-xp 00000000 fd:05 806057                     /home/faisal/sap/linux/nwrfcsdk/lib/libicuuc.so.50
7ffbace3a000-7ffbad03a000 ---p 001d5000 fd:05 806057                     /home/faisal/sap/linux/nwrfcsdk/lib/libicuuc.so.50
7ffbad03a000-7ffbad04a000 r--p 001d5000 fd:05 806057                     /home/faisal/sap/linux/nwrfcsdk/lib/libicuuc.so.50
7ffbad04a000-7ffbad04b000 rw-p 001e5000 fd:05 806057                     /home/faisal/sap/linux/nwrfcsdk/lib/libicuuc.so.50
7ffbad04b000-7ffbad090000 rw-p 00000000 00:00 0
7ffbad090000-7ffbad091000 ---p 00000000 00:00 0
7ffbad091000-7ffbada91000 rw-p 00000000 00:00 0 SIGABRT: abort
PC=0x3800c32495 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x3800c32495
stack: frame={sp:0x7ffdc37dd208, fp:0x0} stack=[0x7ffdc2dded70,0x7ffdc37ddd90)
00007ffdc37dd108:  0000000000000000  0000000000000000
00007ffdc37dd118:  0000000000000000  0000000000000000
00007ffdc37dd128:  0000000000000000  0000000000000000
00007ffdc37dd138:  0000000000000000  0000000000000000
00007ffdc37dd148:  0000000000000000  0000000000000000
00007ffdc37dd158:  0000000000000000  0000000000000000
00007ffdc37dd168:  0000000000000000  0000000000000000
00007ffdc37dd178:  0000000000000000  0000000000000000
00007ffdc37dd188:  0000003800d26d4c  00000c0100000000
00007ffdc37dd198:  00007ffdc37dd2f8  0000000000000000
00007ffdc37dd1a8:  0000000000401660  0000000000000000
00007ffdc37dd1b8:  0000003800ce0cc0  0000000000000002
00007ffdc37dd1c8:  0000000000000004  00007ffdc37dd220
00007ffdc37dd1d8:  0000000000000400  00007ffdc37ddc50
00007ffdc37dd1e8:  0000000000000005  00007ffdc37dd530
00007ffdc37dd1f8:  000000000000005f  0000000000000007
00007ffdc37dd208: <0000003800c33c75  00007ffdc37dd2f8
00007ffdc37dd218:  00007ffdc37dd2e0  00007ffdc37df38a
00007ffdc37dd228:  000000000000000d  0000003800d5798f
00007ffdc37dd238:  0000000000000003  00007ffdc37dd2ea
00007ffdc37dd248:  0000000000000006  0000003800d57993
00007ffdc37dd258:  0000000000000002  0000000000000000
00007ffdc37dd268:  0000000000000000  0000000000000000
00007ffdc37dd278:  0000003800c78650  4000000000000000
00007ffdc37dd288:  0000000000000000  0000000000000000
00007ffdc37dd298:  0000000000000000  0000000000000000
00007ffdc37dd2a8:  0000000000000000  0000000000000020
00007ffdc37dd2b8:  0000000000000000  0000000000000000
00007ffdc37dd2c8:  0000000000000000  0000000000000000
00007ffdc37dd2d8:  0000000000000000  0000000000000000
00007ffdc37dd2e8:  0000000000000000  0000000000000000
00007ffdc37dd2f8:  0000000000000000  0000000000000000
runtime: unknown pc 0x3800c32495
stack: frame={sp:0x7ffdc37dd208, fp:0x0} stack=[0x7ffdc2dded70,0x7ffdc37ddd90)
00007ffdc37dd108:  0000000000000000  0000000000000000
00007ffdc37dd118:  0000000000000000  0000000000000000
00007ffdc37dd128:  0000000000000000  0000000000000000
00007ffdc37dd138:  0000000000000000  0000000000000000
00007ffdc37dd148:  0000000000000000  0000000000000000
00007ffdc37dd158:  0000000000000000  0000000000000000
00007ffdc37dd168:  0000000000000000  0000000000000000
00007ffdc37dd178:  0000000000000000  0000000000000000
00007ffdc37dd188:  0000003800d26d4c  00000c0100000000
00007ffdc37dd198:  00007ffdc37dd2f8  0000000000000000
00007ffdc37dd1a8:  0000000000401660  0000000000000000
00007ffdc37dd1b8:  0000003800ce0cc0  0000000000000002
00007ffdc37dd1c8:  0000000000000004  00007ffdc37dd220
00007ffdc37dd1d8:  0000000000000400  00007ffdc37ddc50
00007ffdc37dd1e8:  0000000000000005  00007ffdc37dd530
00007ffdc37dd1f8:  000000000000005f  0000000000000007
00007ffdc37dd208: <0000003800c33c75  00007ffdc37dd2f8
00007ffdc37dd218:  00007ffdc37dd2e0  00007ffdc37df38a
00007ffdc37dd228:  000000000000000d  0000003800d5798f
00007ffdc37dd238:  0000000000000003  00007ffdc37dd2ea
00007ffdc37dd248:  0000000000000006  0000003800d57993
00007ffdc37dd258:  0000000000000002  0000000000000000
00007ffdc37dd268:  0000000000000000  0000000000000000
00007ffdc37dd278:  0000003800c78650  4000000000000000
00007ffdc37dd288:  0000000000000000  0000000000000000
00007ffdc37dd298:  0000000000000000  0000000000000000
00007ffdc37dd2a8:  0000000000000000  0000000000000020
00007ffdc37dd2b8:  0000000000000000  0000000000000000
00007ffdc37dd2c8:  0000000000000000  0000000000000000
00007ffdc37dd2d8:  0000000000000000  0000000000000000
00007ffdc37dd2e8:  0000000000000000  0000000000000000
00007ffdc37dd2f8:  0000000000000000  0000000000000000

goroutine 1 [syscall]:
runtime.cgocall(0x4b08f0, 0xc00010cdc8, 0xc000000000)
        /data/goLang/NoCGRates/src/runtime/cgocall.go:128 +0x5b fp=0xc00010cd98 sp=0xc00010cd60 pc=0x405f8b
github.com/sap/gorfc/gorfc._Cfunc_free(0xcc3590)
        _cgo_gotypes.go:1086 +0x41 fp=0xc00010cdc8 sp=0xc00010cd98 pc=0x49df41
github.com/sap/gorfc/gorfc.wrapTypeDescription.func1.1()
        /home/faisal/goPath/src/github.com/sap/gorfc/gorfc/gorfc.go:458 +0x5a fp=0xc00010ce08 sp=0xc00010cdc8 pc=0x4aae4a
github.com/sap/gorfc/gorfc.wrapTypeDescription(0xccb2a0, 0xc000016c00, 0x1c, 0x1cb, 0x390, 0xc000130800, 0xa, 0x10, 0x0, 0x0)
        /home/faisal/goPath/src/github.com/sap/gorfc/gorfc/gorfc.go:516 +0x6e5 fp=0xc00010f168 sp=0xc00010ce08 pc=0x4a3335
github.com/sap/gorfc/gorfc.wrapFunctionDescription(0xcc37b0, 0xc000016b40, 0x1b, 0xc000140000, 0x3, 0x4, 0x0, 0x0)
        /home/faisal/goPath/src/github.com/sap/gorfc/gorfc/gorfc.go:614 +0x5cc fp=0xc000110e70 sp=0xc00010f168 pc=0x4a405c
github.com/sap/gorfc/gorfc.(*Connection).GetFunctionDescription(0xc0000841b0, 0x4ed275, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/faisal/goPath/src/github.com/sap/gorfc/gorfc/gorfc.go:1105 +0x133 fp=0xc000111ca8 sp=0xc000110e70 pc=0x4a84c3
main.main()
        /home/faisal/goPath/src/github.com/sap/gorfc/example/hello_gorfc.go:90 +0x11f7 fp=0xc000111f98 sp=0xc000111ca8 pc=0x4b02a7
runtime.main()
        /data/goLang/NoCGRates/src/runtime/proc.go:200 +0x20c fp=0xc000111fe0 sp=0xc000111f98 pc=0x42d62c
runtime.goexit()
        /data/goLang/NoCGRates/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000111fe8 sp=0xc000111fe0 pc=0x454eb1

rax    0x0
rbx    0x400
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x18f77
rsi    0x18f77
rbp    0x7ffdc37ddc50
rsp    0x7ffdc37dd208
r8     0x0
r9     0x4b0bf0
r10    0x8
r11    0x206
r12    0x5
r13    0x7ffdc37dd530
r14    0x5f
r15    0x7
rip    0x3800c32495
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
`

Please help.

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project.
