### ISSUE TITLE
gorfc programs do not work with executables generated in go 1.15 (for windows-64 10)

### ISSUE THREAD

**Issue by paparipote** [SAP/gorfc#26]
Do you know something about this issue?
Go programs contaning gorfc package compile without error under 1.15, but when executing, no output is generated. When I compile with 1.14 it compiles without errors and the output is what I expected.
The same problem happens when compiling and executing program "hello_gorfc.go".
Best regards.

**Comment by bsrdjan** [comment]
The Windows is not supported until #21 fixed

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project.
