### ISSUE TITLE
Error running hello_gorfc.go on CentOS 7

### ISSUE THREAD

**Issue by ChernykhAN** [SAP/gorfc#28]
I having error running hello_gorfc.go

```
Connected: true
Connection attributes map[client:900 codepage:4103 cpicConvId:45417549 dest: host:my_host isoLanguage:RUd kernelRel:753 language:R partnerBytesPerChar:2k partnerCodepage:4103 partnerHost:sap-host partnerIP:10.170.32.32 partnerIPv6:10.170.32.32 partnerRel:740 partnerSystemCodepage:4103 partnerType:3k progName:SAPLSYST rel:753 rfcRole:Ck sysId:CHQ sysNumber:10d trace:0k type:Ek user:MYUSER] 
GORFC error: Error parsing ABAP RFC_DATE field | parsing time "20201124CTv": extra text: "CTv"
```
There is a wrong symbols added after some fields, for ex: isoLanguage:RUd, sysNumber:10d, trace:0k type:Ek
CentOS Linux release 7.9.2009 (Core) 
go version go1.15.5 linux/amd64
nwrfc750P_7-70002752
Tryed on two different CentOS 7 and had the same errors.

The same settings from Ubuntu returns correct result:
```
Connected: true
Connection attributes map[client:900 codepage:4103 cpicConvId:45229127 dest: host:my_host isoLanguage:RU kernelRel:753 language:R partnerBytesPerChar:2 partnerCodepage:4103 partnerHost::sap-host partnerIP:10.170.32.32 partnerIPv6:10.170.32.32 partnerRel:740 partnerSystemCodepage:4103 partnerType:3 progName:SAPLSYST rel:753 rfcRole:C sysId:CHQ sysNumber:10 trace:0 type:E user:MYUSER]
map[RFCCHAR1:A RFCCHAR2:BC RFCCHAR4:ÄBC RFCDATA1:HELLÖ SÄP RFCDATA2:DATA222 RFCDATE:2020-11-24 00:00:00 +0000 UTC RFCFLOAT:1.23456789 RFCHEX3:[255 254 253] RFCINT1:254 RFCINT2:32766 RFCINT4:999999999 RFCTIME:0000-01-01 12:37:33 +0000 UTC]
map[RFCCHAR1:A RFCCHAR2:BC RFCCHAR4:ÄBC RFCDATA1:HELLÖ SÄP RFCDATA2:DATA222 RFCDATE:2020-11-24 00:00:00 +0000 UTC RFCFLOAT:1.23456789 RFCHEX3:[255 254 253] RFCINT1:254 RFCINT2:32766 RFCINT4:999999999 RFCTIME:0000-01-01 12:37:33 +0000 UTC]
2020-11-24 12:37:33.8180975 +0300 MSK m=+0.378176001 time.Time
2020-11-24 00:00:00 +0000 UTC time.Time
2020-11-24 12:37:33.818092 +0300 MSK m=+0.378171001 time.Time
0000-01-01 12:37:33 +0000 UTC time.Time
```

What should I additionally check for run gorfc on CentOS 7? Has anyone successfully run gorfc on CentOS 7?

**Comment by bsrdjan** [comment]
There is a known bug in PL7, causing encoding errors. Please use the PL6 until the fix shipped with PL8.

**Comment by ChernykhAN** [comment]
@bsrdjan, thank you for reply. 
But where can I download PL6? On SAP Marketplace the only PL7 available. 
Can you please give me the download link?

**Comment by bsrdjan** [comment]
Unfortunately only the latest PL is available on SAP Support Portal. If you can create SAP Customer Incident for the BC-MID-RFC-SDK component, I can send you the PL6 or the current PL8 build over that channel. Please let me know the ticket number if you create one.

**Comment by ChernykhAN** [comment]
The ticket number 795183 / 2020 Error running hello_gorfc.go on CentOS 7

**Comment by ChernykhAN** [comment]
@bsrdjan, please send me the PL6 or PL8 in ticket number 795183 / 2020.

**Comment by bsrdjan** [comment]
Could you please use the workaround provided with a45e6b8, until the PL8 fix available.

**Comment by ChernykhAN** [comment]
It works properly now.
Thank you.
