### ISSUE TITLE
while go get github.com/sap/gorfc   no Go files in /go/src/github.com/sap/gorfc

### ISSUE THREAD

**Issue by DongDavid** [SAP/gorfc#29]
go version 1.15.6.

while run `go get github/sap/gorfc`
I get a warning `package github.com/sap/gorfc: no Go files in /go/src/github.com/sap/gorfc` 
```sh
$go get github.com/sap/gorfc
package github.com/sap/gorfc: no Go files in /go/src/github.com/sap/gorfc
```
the go files actually in `/go/src/github.com/sap/gorfc/gorfc/` 
although it can be work ,
还是讲中文吧， 讲英语太累了。。。
新版本的go 在加载这个包的时候， 会抛出这个警告， 虽然它不影响实际使用， 但是这个警告还是处理一下的好。

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project.
