### ISSUE TITLE
 'sapnwrfc.h' file not found

### ISSUE THREAD

**Issue by Supanutw** [SAP/gorfc#30]
fatal error: 'sapnwrfc.h' file not found
#include <sapnwrfc.h>
         ^~~~~~~~~~~~
1 error generated.

<img width="447" alt="Screen Shot 2564-04-28 at 12 43 34" src="https://user-images.githubusercontent.com/15275171/116352448-5d6fe980-a81f-11eb-9f2c-25952d394a02.png">
<img width="703" alt="Screen Shot 2564-04-28 at 12 45 15" src="https://user-images.githubusercontent.com/15275171/116352601-9a3be080-a81f-11eb-887e-d9b6523e3390.png">
****

**Comment by bsrdjan** [comment]
Did you check if the file is in `include` subfolder of `nwrfcsdk` ?

What you exactly try to do, on which platform and which NWRFC SDK version?

**Comment by Supanutw** [comment]
- macOS
- SDK version 7.5
- gorfc v0.1.0

new error
![Screen Shot 2564-04-28 at 14 28 40](https://user-images.githubusercontent.com/15275171/116364108-0ae9f980-a82e-11eb-8830-223b5eadbd9a.png)


<img width="465" alt="Screen Shot 2564-04-28 at 14 26 33" src="https://user-images.githubusercontent.com/15275171/116363885-ccecd580-a82d-11eb-85ed-3e8269e85122.png">

<img width="431" alt="Screen Shot 2564-04-28 at 14 26 39" src="https://user-images.githubusercontent.com/15275171/116363912-d413e380-a82d-11eb-86db-3c448ce16250.png">

**Comment by bsrdjan** [comment]
Closing due to the sunset of the project.
