### ISSUE TITLE
Error on go build step

### ISSUE THREAD

**Issue by justay** [SAP/gorfc#5]
hi,
when  follow the Doc to build the gorfc, get an error message 
`C:\Gops\src\github.com\sap\gorfc\gorfc>go build
#github.com/sap/gorfc/gorfc
In file included from C:/nwrfcsdk/include/sapnwrfc.h:7:0,
                 from .\gorfc.go:41:
C:/nwrfcsdk/include/sapucx.h:562:5: warning: 'align' attribute directive ignored [-Wattributes]
     typedef __declspec(align(16)) SAP_SRAW platform_max_t[16];
     ^
In file included from .\gorfc.go:41:0:
C:/nwrfcsdk/include/sapnwrfc.h:28:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
#pragma warning (disable : 4267)  // disable warning: conversion from 'size_t' to 'const unsigned int'
 ^
In file included from C:/nwrfcsdk/include/sapnwrfc.h:9:0,
                 from .\gorfc.go:41:
C:/nwrfcsdk/include/sapuc.h:853:24: warning: 'sccsidU16' defined but not used [-Wunused-variable]
   static const SAP_UC* sccsidU16 = NULL;
                        ^`
plantform

- os windows 10
- go 1.8

thanks for any help.

**Comment by STiAT** [comment]
It's just a compiler warning, and can safely be ignored. It's in the rfc header files coming with the SAP SDK.

**Comment by SimonWaldherr** [comment]
@justay i added the ```-Wno-unused-variable```-Flag in commit https://github.com/SAP/gorfc/commit/a904f9943b2a296626e82ed9a194bcf0c1973565#diff-5c38aff45e37dbe9ecb92bcb0f79023cR18, but only for builds on Linux. I don't use [gorfc](https://github.com/SAP/gorfc) on Windows, but you could try something similar.

**Comment by JonasDann** [comment]
@justay I will consider this as solved.
